apiVersion: apps/v1
kind: Deployment
metadata:
  name: museum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: museum
  template:
    metadata:
      labels:
        app: museum
    spec:
      containers:
        - name: museum
          image: "{{ .Values.museum.image }}"
          args:
            - "--config"
            - "/etc/ente/museum.yaml"
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: ente-secrets
          volumeMounts:
            - name: museum-config-volume
              mountPath: /etc/ente/museum.yaml
              subPath: museum.yaml
      volumes:
        - name: museum-config-volume
          configMap:
            name: museum-config
