apiVersion: apps/v1
kind: Deployment
metadata:
  name: museum
  namespace: ente
spec:
  replicas: 1
  selector:
    matchLabels:
      app: museum
  template:
    metadata:
      labels:
        app: museum
    spec:
      volumes:
        - name: museum-config
          configMap:
            name: museum-config
      containers:
        - name: museum
          image: "{{ .Values.museum.image }}"
          command: ["./museum"]
          args:
            - "--config"
            - "/etc/ente/museum.yaml"
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: ente-secrets
          volumeMounts:
            - name: museum-config
              mountPath: /etc/ente
      # Optional init container to verify the config file exists
      initContainers:
        - name: check-config
          image: busybox
          command: ["sh", "-c"]
          args:
            - "ls -l /etc/ente/museum.yaml; cat /etc/ente/museum.yaml"
          volumeMounts:
            - name: museum-config
              mountPath: /etc/ente
