apiVersion: v1
kind: Secret
metadata:
  name: ente-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgres.password }}
  MINIO_ROOT_USER: {{ .Values.minio.accessKey }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.secretKey }}
  MUSEUM_DB_PASSWORD: {{ .Values.museum.config.db.password }}
  MUSEUM_ENCRYPTION_KEY: {{ .Values.museum.config.encryptionKey }}
  MUSEUM_HASH_KEY: {{ .Values.museum.config.hashKey }}
  MUSEUM_JWT_SECRET: {{ .Values.museum.config.jwtSecret }}